export type PipelineStep = {
  id: string;
  phase: number;
  phaseTitle: string;
  title: string;
  description: string;
  instructions: string[] | { mac: string[]; windows: string[]; linux: string[] };
  validateEndpoint: string;
  resourceLabel: string;
};

export type CloudPath = 'aws' | 'azure';

export const AWS_PHASES = [
  { number: 0, title: 'Setup', description: 'Account, CLI & Budget' },
  { number: 1, title: 'Create Pipeline Resources', description: 'S3 + Kinesis + Firehose' },
  { number: 2, title: 'Run the Pipeline', description: 'Send data & verify flow' },
  { number: 3, title: 'Catalog & Query', description: 'Glue + Athena' },
  { number: 4, title: 'Cleanup', description: 'Delete resources to avoid charges' },
];

export const AZURE_PHASES = [
  { number: 0, title: 'Setup', description: 'Account, CLI & Budget' },
  { number: 1, title: 'Create Pipeline Resources', description: 'ADLS + Event Hubs' },
  { number: 2, title: 'Run the Pipeline', description: 'Send data & verify capture' },
  { number: 3, title: 'Query with Synapse', description: 'Synapse workspace + SQL' },
  { number: 4, title: 'Cleanup', description: 'Delete resources to avoid charges' },
];

export const AWS_STEPS: PipelineStep[] = [
  // ─── Phase 0: Setup ───
  {
    id: 'aws-cli',
    phase: 0,
    phaseTitle: 'Setup',
    title: 'Install AWS CLI',
    description: 'Install the AWS Command Line Interface on your machine.',
    instructions: {
      mac: [
        'Open the Terminal app (press Cmd+Space, type "Terminal", press Enter).',
        'Check if Homebrew is installed: type "brew --version" and press Enter.',
        'If Homebrew is NOT installed: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"',
        'Wait for Homebrew to finish installing (2-3 minutes).',
        'Install AWS CLI: type "brew install awscli" and press Enter.',
        'Wait for installation to complete.',
        'Close this Terminal window (Cmd+Q).',
        'Open a new Terminal window.',
        'Verify: type "aws --version" and press Enter.',
        'You should see "aws-cli/2.x.x" — you\'re done!',
      ],
      windows: [
        'Open your browser and go to: https://aws.amazon.com/cli/',
        'Click the "Download MSI Installer" button (64-bit).',
        'Open Downloads folder, double-click the .msi file.',
        'Click "Next" through the installer with all defaults.',
        'Click "Install" (approve admin prompt if asked).',
        'Click "Finish" when done.',
        'Close any open Command Prompt windows.',
        'Open a NEW Command Prompt: press Win+R, type "cmd", Enter.',
        'Type "aws --version" and press Enter.',
        'You should see "aws-cli/2.x.x" — you\'re done!',
      ],
      linux: [
        'Open your terminal.',
        'Download: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"',
        'Unzip: unzip awscliv2.zip',
        'Install: sudo ./aws/install',
        'Enter your password when prompted.',
        'Verify: type "aws --version" and press Enter.',
        'You should see "aws-cli/2.x.x" — you\'re done!',
      ],
    },
    validateEndpoint: '/api/validate/setup/aws-cli',
    resourceLabel: '',
  },
  {
    id: 'aws-configure',
    phase: 0,
    phaseTitle: 'Setup',
    title: 'Configure AWS Credentials',
    description: 'Create an IAM user with access keys and configure the CLI.',
    instructions: [
      'Sign in to AWS Console: https://console.aws.amazon.com/',
      'Search "IAM" in the top bar → click IAM.',
      'Left sidebar → "Users" → click "Create user".',
      'Username: "pipeline-admin" → click Next.',
      'Select "Attach policies directly" → search "AdministratorAccess" → check it → Next → Create user.',
      'Click on your new user name → "Security credentials" tab.',
      'Scroll to "Access keys" → "Create access key".',
      'Use case: select "Command Line Interface (CLI)" → check confirmation → Next → Create.',
      '⚠️ COPY both the Access Key ID and Secret Access Key NOW — you cannot see the secret again!',
      'In your terminal, run: aws configure',
      'Paste Access Key ID when prompted.',
      'Paste Secret Access Key when prompted.',
      'Default region: us-east-1',
      'Default output: json',
      'Verify: run "aws sts get-caller-identity" — should show your Account ID.',
    ],
    validateEndpoint: '/api/validate/setup/aws-credentials',
    resourceLabel: '',
  },
  {
    id: 'aws-budget',
    phase: 0,
    phaseTitle: 'Setup',
    title: 'Set Budget Alert',
    description: 'Protect yourself from surprise charges with a zero-spend budget.',
    instructions: [
      'In AWS Console, search "Budgets" → click "AWS Budgets".',
      'Click "Create a budget".',
      'Select "Use a template" → choose "Zero spend budget".',
      'Budget name: "FreeTierGuard".',
      'Email: enter your email for alerts.',
      'Click "Create budget".',
      'Also: go to Billing → "Billing preferences" → enable "Receive AWS Free Tier usage alerts" → save.',
    ],
    validateEndpoint: '/api/validate/setup/aws-budget',
    resourceLabel: 'Budget Name',
  },

  // ─── Phase 1: Create Pipeline Resources ───
  {
    id: 'aws-s3',
    phase: 1,
    phaseTitle: 'Create Pipeline Resources',
    title: 'Create S3 Bucket (Data Lake)',
    description: 'This bucket is your data lake — where Firehose delivers the streaming data.',
    instructions: [
      'AWS Console → search "S3" → click S3.',
      'Click "Create bucket".',
      'Bucket name: a globally unique name (e.g., "my-pipeline-data-123456").',
      'Region: US East (N. Virginia) us-east-1.',
      'Block Public Access: leave all checked.',
      'Everything else: leave defaults.',
      'Click "Create bucket".',
      'Verify: click your bucket name — it opens (empty for now).',
    ],
    validateEndpoint: '/api/validate/aws/s3',
    resourceLabel: 'S3 Bucket Name',
  },
  {
    id: 'aws-kinesis',
    phase: 1,
    phaseTitle: 'Create Pipeline Resources',
    title: 'Create Kinesis Data Stream (Ingestion)',
    description: 'Kinesis is the entry point — producers send events here in real time.',
    instructions: [
      'AWS Console → search "Kinesis" → click Amazon Kinesis.',
      'Left sidebar → "Data streams" → click "Create data stream".',
      'Stream name: "my-pipeline-stream".',
      'Capacity mode: "On-demand" (auto-scales).',
      'Click "Create data stream".',
      'Wait until Status becomes "Active" (10-20 seconds).',
      '⚠️ Kinesis is NOT free tier (~$0.04/hr). We will delete it at the end.',
    ],
    validateEndpoint: '/api/validate/aws/kinesis',
    resourceLabel: 'Stream Name',
  },
  {
    id: 'aws-firehose',
    phase: 1,
    phaseTitle: 'Create Pipeline Resources',
    title: 'Create Firehose (Kinesis → S3 Delivery)',
    description: 'Firehose reads from Kinesis and writes batched data to S3 automatically with partitioned paths.',
    instructions: [
      'AWS Console → search "Firehose" → click Amazon Data Firehose.',
      'Click "Create Firehose stream".',
      'Source: "Amazon Kinesis Data Streams" → Browse → select "my-pipeline-stream".',
      'Firehose stream name: "my-pipeline-firehose".',
      'Destination: Amazon S3 → Browse → select your bucket.',
      'S3 prefix: data/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/',
      'Error prefix: errors/!{firehose:error-output-type}/',
      'Buffer size: 1 MiB, Buffer interval: 60 seconds.',
      'Permissions: "Create or update IAM role" (auto-creates).',
      'Click "Create Firehose stream".',
      'Wait until Status: "Active" (1-2 minutes).',
      '⚠️ Firehose is NOT free tier. Delete at end.',
    ],
    validateEndpoint: '/api/validate/aws/firehose',
    resourceLabel: 'Firehose Name',
  },

  // ─── Phase 2: Run the Pipeline ───
  {
    id: 'aws-send-data',
    phase: 2,
    phaseTitle: 'Run the Pipeline',
    title: 'Send Test Data to Kinesis',
    description: 'Push sample events into your stream and watch them flow through the pipeline.',
    instructions: [
      'Open your terminal.',
      'Run this command to send 10 test records:',
      'for i in {1..10}; do aws kinesis put-record --stream-name my-pipeline-stream --data $(echo -n \'{"user":"user_\'$i\'","event":"click","page":"/home","ts":\'$(date +%s)\'}\' | base64) --partition-key "user_$i"; done',
      'You should see a response with "ShardId" and "SequenceNumber" for each record — this means data entered Kinesis.',
      'Each record is a JSON event with user_id, event type, page, and timestamp.',
      'Firehose will automatically pick these up and deliver to S3 within 60 seconds (your buffer interval).',
    ],
    validateEndpoint: '/api/validate/aws/kinesis',
    resourceLabel: 'Stream Name',
  },
  {
    id: 'aws-verify-s3',
    phase: 2,
    phaseTitle: 'Run the Pipeline',
    title: 'Verify Data Landed in S3',
    description: 'Check that Firehose delivered your data to S3 with the partitioned folder structure.',
    instructions: [
      '⏳ Wait at least 60-90 seconds after sending data (Firehose buffer interval).',
      'AWS Console → S3 → click your bucket.',
      'You should see a "data/" folder. Click into it.',
      'You\'ll see partitioned folders: year=2026/ → month=06/ → day=14/ → hour=XX/',
      'Inside the hour folder, you\'ll find .gz files — these contain your records!',
      'To verify via CLI: aws s3 ls s3://YOUR-BUCKET/data/ --recursive',
      'You should see files listed. If empty, wait another minute and refresh.',
      'This partitioned structure is KEY to hyperscaling — queries only read relevant partitions.',
      'Download a file to inspect: aws s3 cp s3://YOUR-BUCKET/data/year=.../file.gz . && gunzip file.gz && cat file',
    ],
    validateEndpoint: '/api/validate/aws/s3',
    resourceLabel: 'S3 Bucket Name',
  },

  // ─── Phase 3: Catalog & Query ───
  {
    id: 'aws-glue',
    phase: 3,
    phaseTitle: 'Catalog & Query',
    title: 'Create Glue Database & Run Crawler',
    description: 'Glue discovers your data schema automatically and makes it queryable by SQL engines.',
    instructions: [
      'AWS Console → search "Glue" → click AWS Glue.',
      'Left sidebar → "Databases" → click "Add database".',
      'Name: "my_pipeline_db" → click "Create database".',
      'Left sidebar → "Crawlers" → click "Create crawler".',
      'Name: "my-pipeline-crawler" → Next.',
      'Add data source → S3 → Browse → select your bucket → navigate to "data/" folder → choose it.',
      'Click "Add an S3 data source" → Next.',
      'IAM Role: "Create new IAM role" → suffix: "pipeline-crawler" → Create → Next.',
      'Target database: "my_pipeline_db" → Next → Create crawler.',
      'Select your crawler → click "Run".',
      'Wait until Last run status: "Succeeded" (1-2 minutes).',
      'Go to "Tables" in left sidebar — you should see a "data" table with columns matching your JSON.',
      '⚠️ Crawler costs ~$0.01 per run.',
    ],
    validateEndpoint: '/api/validate/aws/glue',
    resourceLabel: 'Database Name',
  },
  {
    id: 'aws-athena',
    phase: 3,
    phaseTitle: 'Catalog & Query',
    title: 'Query Your Pipeline Data with Athena',
    description: 'Run serverless SQL queries directly on your S3 data — no servers, no loading, pay per query.',
    instructions: [
      'AWS Console → search "Athena" → click Amazon Athena.',
      'First time: click "Settings" → "Manage" → enter a results location: s3://YOUR-BUCKET-athena-results/ (create this bucket in S3 if needed) → Save.',
      'Click "Editor" tab.',
      'Left panel: select Database → "my_pipeline_db".',
      'You should see a table called "data" listed.',
      'In the query editor, paste: SELECT * FROM data LIMIT 10;',
      'Click "Run" — your pipeline data appears as structured rows!',
      'Now try partition-pruned query: SELECT * FROM data WHERE year=\'2026\' AND month=\'06\';',
      'Check "Query stats" at bottom — notice "Data scanned" is small. This is partitioning at work.',
      'Try aggregation: SELECT event, COUNT(*) as cnt FROM data GROUP BY event;',
      'You just built a complete real-time pipeline: Events → Kinesis → Firehose → S3 → Glue → Athena 🎉',
    ],
    validateEndpoint: '/api/validate/aws/athena',
    resourceLabel: 'Results Bucket Name',
  },

  // ─── Phase 4: Cleanup ───
  {
    id: 'aws-cleanup',
    phase: 4,
    phaseTitle: 'Cleanup',
    title: 'Delete All Resources (Stop Charges)',
    description: 'Delete non-free-tier resources to stop incurring charges. Keep this step for when you\'re done practicing.',
    instructions: [
      'DELETE FIREHOSE: Console → Firehose → select "my-pipeline-firehose" → Delete → confirm.',
      'DELETE KINESIS: Console → Kinesis → Data streams → select "my-pipeline-stream" → Delete → confirm.',
      'DELETE GLUE CRAWLER: Console → Glue → Crawlers → select → Delete.',
      'DELETE GLUE DATABASE: Console → Glue → Databases → select "my_pipeline_db" → Delete.',
      'DELETE S3 (optional): Console → S3 → select bucket → "Empty" first → then "Delete".',
      'Or via CLI (faster):',
      'aws firehose delete-delivery-stream --delivery-stream-name my-pipeline-firehose',
      'aws kinesis delete-stream --stream-name my-pipeline-stream',
      'aws glue delete-crawler --name my-pipeline-crawler',
      'aws glue delete-database --name my_pipeline_db',
      'aws s3 rb s3://YOUR-BUCKET --force',
      'Verify: check your Billing dashboard in 24 hours — charges should stop.',
    ],
    validateEndpoint: '/api/validate/setup/aws-cli',
    resourceLabel: '',
  },
];

export const AZURE_STEPS: PipelineStep[] = [
  // ─── Phase 0: Setup ───
  {
    id: 'azure-cli',
    phase: 0,
    phaseTitle: 'Setup',
    title: 'Install Azure CLI',
    description: 'Install the Azure Command Line Interface.',
    instructions: {
      mac: [
        'Open the Terminal app (press Cmd+Space, type "Terminal", press Enter).',
        'Check if Homebrew is installed: type "brew --version" and press Enter.',
        'If Homebrew is NOT installed, install it first: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"',
        'Wait for Homebrew installation to finish (may take 2-3 minutes).',
        'Now install Azure CLI: type "brew update && brew install azure-cli" and press Enter.',
        'Wait for installation to complete (1-2 minutes, you\'ll see progress).',
        'Close this Terminal window completely (Cmd+Q).',
        'Open a new Terminal window (Cmd+Space → "Terminal" → Enter).',
        'Verify: type "az --version" and press Enter.',
        'You should see "azure-cli 2.x.x" at the top. If you see this, you\'re done!',
      ],
      windows: [
        'Open your web browser and go to: https://aka.ms/installazurecliwindows',
        'The MSI installer file will download automatically.',
        'Open your Downloads folder and double-click the file "azure-cli-x.x.x-x64.msi".',
        'Click "Next" on the welcome screen.',
        'Accept the license agreement → click "Next".',
        'Leave the install location as default → click "Next".',
        'Click "Install" (you may need to click "Yes" on the admin prompt).',
        'Wait for installation to complete → click "Finish".',
        'Close any open Command Prompt or PowerShell windows.',
        'Open a NEW Command Prompt: press Win+R, type "cmd", press Enter.',
        'Type "az --version" and press Enter.',
        'You should see "azure-cli 2.x.x" at the top. If you see this, you\'re done!',
      ],
      linux: [
        'Open your terminal.',
        'Run this single command to install: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash',
        'Enter your password when prompted (you won\'t see characters as you type — that\'s normal).',
        'Wait for installation to complete (1-2 minutes).',
        'Verify: type "az --version" and press Enter.',
        'You should see "azure-cli 2.x.x" at the top. If you see this, you\'re done!',
        'If you get a "command not found" error, try closing and reopening your terminal.',
      ],
    },
    validateEndpoint: '/api/validate/setup/azure-cli',
    resourceLabel: '',
  },
  {
    id: 'azure-login',
    phase: 0,
    phaseTitle: 'Setup',
    title: 'Create Azure Account & Login',
    description: 'Sign up for Azure (free $200 credit) and authenticate the CLI.',
    instructions: [
      'If no account: go to https://azure.microsoft.com/free/ → "Start free" → sign up.',
      'In terminal, run: az login',
      'Browser opens → sign in with your Microsoft account.',
      'Terminal shows your subscription info. Look for "state": "Enabled".',
      'If multiple subscriptions: az account set --subscription "YOUR_ID"',
      'Verify: az account show — displays subscription name and ID.',
    ],
    validateEndpoint: '/api/validate/setup/azure-login',
    resourceLabel: '',
  },
  {
    id: 'azure-budget',
    phase: 0,
    phaseTitle: 'Setup',
    title: 'Set Budget Alert',
    description: 'Create a spending limit with email notifications.',
    instructions: [
      'Azure Portal → search "Cost Management" → click it.',
      'Left sidebar → "Budgets" → click "+ Add".',
      'Name: "FreeTierGuard", Reset period: Monthly, Amount: $5.',
      'Click Next.',
      'Alert at 80% threshold, type: Actual.',
      'Enter your email → Create.',
    ],
    validateEndpoint: '/api/validate/setup/azure-budget',
    resourceLabel: 'Budget Name',
  },

  // ─── Phase 1: Create Pipeline Resources ───
  {
    id: 'azure-rg',
    phase: 1,
    phaseTitle: 'Create Pipeline Resources',
    title: 'Create Resource Group',
    description: 'A resource group is a container for all your Azure resources — makes cleanup easy.',
    instructions: [
      'Azure Portal → search "Resource groups" → click it.',
      'Click "+ Create".',
      'Subscription: select yours.',
      'Resource group name: "rg-pipeline".',
      'Region: "(US) East US 2".',
      'Click "Review + create" → "Create".',
      'This takes a few seconds.',
    ],
    validateEndpoint: '/api/validate/setup/azure-login',
    resourceLabel: '',
  },
  {
    id: 'azure-adls',
    phase: 1,
    phaseTitle: 'Create Pipeline Resources',
    title: 'Create ADLS Gen2 Storage (Data Lake)',
    description: 'Azure Data Lake Storage Gen2 — your data lake with hierarchical file system.',
    instructions: [
      'Azure Portal → search "Storage accounts" → click it.',
      'Click "+ Create".',
      'Resource group: "rg-pipeline".',
      'Storage account name: globally unique, lowercase (e.g., "mypipelinedata01").',
      'Region: East US 2.',
      'Performance: Standard. Redundancy: LRS (cheapest).',
      'Click "Next: Advanced".',
      '⚠️ CRITICAL: Check ✅ "Enable hierarchical namespace" — this makes it ADLS Gen2!',
      'Click "Review + create" → "Create". Wait ~30 seconds.',
      'Go to resource → "Containers" → create containers named "raw" and "curated".',
    ],
    validateEndpoint: '/api/validate/azure/adls',
    resourceLabel: 'Storage Account Name',
  },
  {
    id: 'azure-eventhubs',
    phase: 1,
    phaseTitle: 'Create Pipeline Resources',
    title: 'Create Event Hubs with Capture (Ingestion → ADLS)',
    description: 'Event Hubs receives streaming events and Capture auto-writes them to your data lake.',
    instructions: [
      'Azure Portal → search "Event Hubs" → click it.',
      'Click "+ Create".',
      'Resource group: "rg-pipeline".',
      'Namespace: unique name (e.g., "my-pipeline-eh").',
      'Location: East US 2. Pricing: Standard. Throughput Units: 1.',
      'Click "Review + create" → "Create". Wait for deployment.',
      'Go to resource → click "+ Event Hub".',
      'Name: "clickstream". Partition count: 4.',
      'Click "Capture" tab → toggle ON.',
      'Time window: 300s. Size window: 300 MB.',
      'Capture provider: Azure Blob Storage.',
      '"Select Container" → your storage account → "raw" container → Select.',
      'Name format: {Namespace}/{EventHub}/year={Year}/month={Month}/day={Day}/hour={Hour}/{Minute}/{Second}',
      'Click "Create".',
      '⚠️ Standard tier Event Hubs is not free. Delete when done.',
    ],
    validateEndpoint: '/api/validate/azure/eventhubs',
    resourceLabel: 'Namespace Name',
  },

  // ─── Phase 2: Run the Pipeline ───
  {
    id: 'azure-send-data',
    phase: 2,
    phaseTitle: 'Run the Pipeline',
    title: 'Send Test Events to Event Hubs',
    description: 'Push sample events and watch them flow to your data lake via Capture.',
    instructions: [
      'Install the Python SDK: pip install azure-eventhub',
      'Get your connection string: Azure Portal → your Event Hubs namespace → "Shared access policies" → "RootManageSharedAccessKey" → copy "Connection string—primary key".',
      'Create a file "send_events.py" with this code:',
      'import json, time, random; from azure.eventhub import EventHubProducerClient, EventData',
      'conn = "YOUR_CONNECTION_STRING"',
      'producer = EventHubProducerClient.from_connection_string(conn, eventhub_name="clickstream")',
      'with producer: batch = producer.create_batch(); [batch.add(EventData(json.dumps({"user": f"user_{i}", "event": random.choice(["click","view","purchase"]), "page": "/home", "ts": int(time.time())}))) for i in range(20)]; producer.send_batch(batch); print("Sent 20 events!")',
      'Run: python send_events.py',
      'You should see "Sent 20 events!".',
    ],
    validateEndpoint: '/api/validate/azure/eventhubs',
    resourceLabel: 'Namespace Name',
  },
  {
    id: 'azure-verify-adls',
    phase: 2,
    phaseTitle: 'Run the Pipeline',
    title: 'Verify Data Landed in ADLS',
    description: 'Check that Event Hubs Capture wrote Avro files to your data lake.',
    instructions: [
      '⏳ Wait 5 minutes (Capture interval is 300 seconds).',
      'Azure Portal → your storage account → "Containers" → click "raw".',
      'You should see folders: my-pipeline-eh/clickstream/year=2026/month=06/day=14/hour=XX/...',
      'Click through the folders — you\'ll find .avro files inside.',
      'These files contain your events in Avro format.',
      'Via CLI: az storage fs file list --file-system raw --account-name YOUR_ACCOUNT --auth-mode login --recursive true',
      'The partitioned folder structure (year/month/day/hour) enables efficient querying.',
      'If no files appear, wait another 5 minutes and refresh.',
    ],
    validateEndpoint: '/api/validate/azure/adls',
    resourceLabel: 'Storage Account Name',
  },

  // ─── Phase 3: Query with Synapse ───
  {
    id: 'azure-synapse',
    phase: 3,
    phaseTitle: 'Query with Synapse',
    title: 'Create Synapse Workspace',
    description: 'Synapse lets you query your data lake with serverless SQL — no infrastructure to manage.',
    instructions: [
      'Azure Portal → search "Synapse" → click "Azure Synapse Analytics".',
      'Click "+ Create".',
      'Resource group: "rg-pipeline".',
      'Workspace name: unique (e.g., "my-pipeline-synapse").',
      'Region: East US 2.',
      'Storage: select your ADLS account. File system: "curated".',
      'Click "Next: Security" → SQL admin: "sqladmin", password: choose a strong one.',
      'Click "Review + create" → "Create". (Takes 2-5 minutes.)',
      'After deployed: go to resource → click "Open Synapse Studio".',
      'Also: go to Networking → add your client IP to the firewall → Save.',
    ],
    validateEndpoint: '/api/validate/azure/synapse',
    resourceLabel: 'Workspace Name',
  },
  {
    id: 'azure-query',
    phase: 3,
    phaseTitle: 'Query with Synapse',
    title: 'Query Data Lake with Serverless SQL',
    description: 'Run SQL queries directly on your Avro/Parquet files in ADLS — no data loading needed.',
    instructions: [
      'In Synapse Studio, click "Develop" (left sidebar, code icon).',
      'Click "+" → "SQL script".',
      'Connect to: "Built-in" (serverless SQL pool).',
      'Paste this query (replace YOUR_ACCOUNT with your storage account name):',
      'SELECT TOP 10 * FROM OPENROWSET(BULK \'abfss://raw@YOUR_ACCOUNT.dfs.core.windows.net/my-pipeline-eh/clickstream/**\', FORMAT=\'PARQUET\') AS rows;',
      'Click "Run" — your pipeline events appear as structured rows!',
      'Try: SELECT Body FROM OPENROWSET(...) — the Body column contains your JSON events.',
      'You built a complete pipeline: Events → Event Hubs → Capture → ADLS → Synapse SQL 🎉',
      '⚠️ Synapse serverless charges $5/TB scanned.',
    ],
    validateEndpoint: '/api/validate/azure/synapse',
    resourceLabel: 'Workspace Name',
  },

  // ─── Phase 4: Cleanup ───
  {
    id: 'azure-cleanup',
    phase: 4,
    phaseTitle: 'Cleanup',
    title: 'Delete All Resources (Stop Charges)',
    description: 'Delete the resource group to remove everything at once.',
    instructions: [
      'The easiest cleanup in Azure: delete the resource group. This removes EVERYTHING inside it.',
      'Azure Portal → "Resource groups" → click "rg-pipeline".',
      'Click "Delete resource group" at the top.',
      'Type the resource group name to confirm → click "Delete".',
      'Or via CLI: az group delete --name rg-pipeline --yes --no-wait',
      'This deletes: storage account, Event Hubs, Synapse workspace, and all data.',
      'Verify in 10 minutes: the resource group should be gone from the list.',
      'Check Cost Management in 24 hours to confirm no more charges.',
    ],
    validateEndpoint: '/api/validate/setup/azure-login',
    resourceLabel: '',
  },
];
